### ISSUE TITLE
Missing dependency? fs/promises and PDF cannot be opened by Chrome

### ISSUE THREAD

**Issue by ghost** [PegasisForever/typora-parser#5]
Hi, 
Ubuntu 20.04
```
sudo apt install npm
sudo npm install -g typora-parser

[05:43 PM]-[ikennedy@HUB-9K9LPN3]-[~]-
$ typora-export -h
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/typora-parser/build/bin/typoraExport.js:18:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)


[05:45 PM]-[ikennedy@HUB-9K9LPN3]-[~]-
$ typora-export --output file.pdf file.md
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/typora-parser/build/bin/typoraExport.js:18:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by ghost** [comment]
Solution:
```
[05:49 PM]-[ikennedy@HUB-9K9LPN3]-[~]-
$ nodejs --version
v10.19.0

# Do this
sudo apt install npm
sudo npm install
sudo npm install -g typora-parser
sudo apt install -y curl
curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt install -y nodejs
nodejs --version # no longer used
node --version


[05:55 PM]-[ikennedy@HUB-9K9LPN3]-[~]-
$ node --version
v18.15.0
```

Then your "typora-export -h" works as you advertise.

Sorry for this noise, but maybe it will help someone else :) 

Cheers!

**Comment by ghost** [comment]
Now cannot open:
![image](https://user-images.githubusercontent.com/76818228/229241277-dbcf317c-10f9-47cd-ad2c-19013f820842.png)

[05:59 PM]-[ikennedy@HUB-9K9LPN3]-[~]-
$ typora-export --output file.pdf file.md

**Comment by ghost** [comment]
well, I guess I have not had enough rest 😆 

This tool is a MD to HTML not a MD to PDF ... my bad

Not this:
```
typora-export --output file.pdf file.md
```

Dothis:
```
typora-export --output file.html file.md
```

**Comment by ghost** [comment]
Followed the rest of instructions and I have a perfect HTML file that matches Typora PDF export. THanks!
